"""Build the claude.ai artifact copy of the app (D004, D017, D027).

Writes build/artifact/index.html (the page without <!doctype>/<html>/<head>/<body>, which
claude.ai adds when publishing) plus css/, js/ and vendor/, and build/artifact/files.json mapping
each published path to its file. Publish index.html with those files to the same artifact URL.

Run `npm run build:css` first if you changed any classes, so css/tailwind.css is current.
Install-to-home-screen features (manifest, icons, service worker) are left out: they only apply
to the hosted web app (dist/).
"""
import json, os, re, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'build', 'artifact')

if not os.path.exists(os.path.join(ROOT, 'css', 'tailwind.css')):
    raise SystemExit('css/tailwind.css is missing. Run `npm run build:css` first.')

shutil.rmtree(OUT, ignore_errors=True)
os.makedirs(OUT)
s = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
head = re.search(r'<head>(.*?)</head>', s, re.S).group(1)
body_tag = re.search(r'<body([^>]*)>', s)
body_class = re.search(r'class="([^"]*)"', body_tag.group(1)).group(1)
body = s[body_tag.end():s.rindex('</body>')]
head = re.sub(r'\s*<meta[^>]*>', '', head)
head = re.sub(r'\s*<link rel="(manifest|icon|apple-touch-icon)"[^>]*>', '', head)
head = re.sub(r'\s*<!--.*?-->', '', head, flags=re.S)
with open(os.path.join(OUT, 'index.html'), 'w', encoding='utf-8') as f:
    f.write(head.strip() + '\n<script src="js/artifact-shell.js"></script>\n' + body.strip() + '\n')

files = {}
for d in ('css', 'js', 'vendor'):
    shutil.copytree(os.path.join(ROOT, d), os.path.join(OUT, d))
# Classes that the published page's own <html>/<body> need (claude.ai writes those tags)
with open(os.path.join(OUT, 'js', 'artifact-shell.js'), 'w', encoding='utf-8') as f:
    f.write('// Generated by scripts/build_artifact.py\n'
            'document.documentElement.classList.add("h-full");\n'
            'document.documentElement.lang = "en-GB";\n'
            'document.body.className = ' + json.dumps(body_class) + ';\n')
for dirpath, _, names in os.walk(OUT):
    for name in sorted(names):
        full = os.path.join(dirpath, name)
        rel = os.path.relpath(full, OUT).replace(os.sep, '/')
        if rel not in ('index.html', 'files.json') and not rel.endswith('LICENSE'):
            files[rel] = full
with open(os.path.join(OUT, 'files.json'), 'w', encoding='utf-8') as f:
    json.dump(dict(sorted(files.items())), f, indent=1)
print('Built', OUT, 'with', len(files), 'files')
